USE didactinaut_dev;

DELIMITER $$
DROP TRIGGER IF EXISTS TR_AFTER_INSERT_ON_SECTIONS $$

CREATE TRIGGER TR_AFTER_INSERT_ON_SECTIONS
AFTER INSERT
ON Sections FOR EACH ROW
BEGIN
	UPDATE Courses AS C
    SET
		C.last_update = CURRENT_TIME()
	WHERE
		C.course_id = New.course_id;
END $$
DELIMITER ;
